<a href="https://colab.research.google.com/github/obeabi/TorchStudy/blob/main/PyTorch_Tut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Tutorial

In [4]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
print("Import Successful!")

Import Successful!


In [5]:
torch.empty(3,3)

tensor([[4.0197e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22]])

In [10]:
x = torch.tensor([3,4.3,5])
type(x)

torch.Tensor

In [11]:
print(x)

tensor([3.0000, 4.3000, 5.0000])


In [14]:
x = x.new_zeros(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [15]:
x.shape

torch.Size([5, 3])

In [16]:
x.size()

torch.Size([5, 3])

In [17]:
x = torch.rand_like(x,dtype = torch.float64)
print(x)

tensor([[0.2340, 0.2104, 0.3733],
        [0.6836, 0.2278, 0.0105],
        [0.6089, 0.7068, 0.1448],
        [0.5872, 0.9578, 0.1407],
        [0.5213, 0.8182, 0.2439]], dtype=torch.float64)


In [19]:
y = torch.randn((5,3), dtype = torch.float64)
print(y)

tensor([[-0.2503, -1.3996, -0.6188],
        [ 1.1900,  1.0836, -0.8590],
        [ 0.1052, -2.1418,  0.8983],
        [ 0.3015,  0.5933, -0.8034],
        [ 1.0030, -1.1387,  0.4111]], dtype=torch.float64)


In [22]:
print(x+y)

tensor([[-0.0163, -1.1891, -0.2455],
        [ 1.8736,  1.3114, -0.8485],
        [ 0.7141, -1.4350,  1.0431],
        [ 0.8887,  1.5512, -0.6627],
        [ 1.5243, -0.3206,  0.6551]], dtype=torch.float64)


In [24]:
result = torch.empty(5,3)
torch.add(x,y,out= result)
print(result)

tensor([[ 0.2177, -0.9787,  0.1278],
        [ 2.5572,  1.5392, -0.8380],
        [ 1.3231, -0.7282,  1.1880],
        [ 1.4759,  2.5090, -0.5220],
        [ 2.0456,  0.4976,  0.8990]])


In [23]:
y.add_(x)

tensor([[-0.0163, -1.1891, -0.2455],
        [ 1.8736,  1.3114, -0.8485],
        [ 0.7141, -1.4350,  1.0431],
        [ 0.8887,  1.5512, -0.6627],
        [ 1.5243, -0.3206,  0.6551]], dtype=torch.float64)

In [26]:
x.copy_(y)
print(x)

tensor([[-0.0163, -1.1891, -0.2455],
        [ 1.8736,  1.3114, -0.8485],
        [ 0.7141, -1.4350,  1.0431],
        [ 0.8887,  1.5512, -0.6627],
        [ 1.5243, -0.3206,  0.6551]], dtype=torch.float64)


In [28]:
z = y.view(-1,15)
z.size()

torch.Size([1, 15])

In [29]:
print(x)

tensor([[-0.0163, -1.1891, -0.2455],
        [ 1.8736,  1.3114, -0.8485],
        [ 0.7141, -1.4350,  1.0431],
        [ 0.8887,  1.5512, -0.6627],
        [ 1.5243, -0.3206,  0.6551]], dtype=torch.float64)


In [30]:
x[:,-1]

tensor([-0.2455, -0.8485,  1.0431, -0.6627,  0.6551], dtype=torch.float64)

In [31]:
x = torch.randn(1)
print(x)

tensor([0.8196])


In [32]:
print(x.item())

0.8196478486061096


In [37]:
a = np.ones((5,6))
b = torch.from_numpy(a)
np.add(a,2, out = a)
print(a)
print(b)

[[3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]]
tensor([[3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3., 3.]], dtype=torch.float64)


In [40]:
x = torch.ones((2,2),requires_grad= True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [42]:
y = torch.add(x,2)
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [43]:
y.grad_fn

In [44]:
a = torch.randn(3,4)
a = ((a - 1)/ (a+4))
print(a)

tensor([[-0.0441, -0.4247, -0.0188, -0.2008],
        [-0.5485, -0.3682, -0.5726,  0.0149],
        [-1.0000, -0.5606, -0.4048,  0.1720]])


In [46]:
print(a.grad_fn)

None


In [48]:
print(a.requires_grad)

False


In [63]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
z = y * x * 3
out = z.mean()

print(z, out)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<MulBackward0>) tensor(9., grad_fn=<MeanBackward0>)


In [64]:
print(out.backward())

None


In [66]:
print(x.grad)

tensor([[3., 3.],
        [3., 3.]])


## ANN 

## Step 1: Build NN Archeteicture

In [77]:
# import libraries
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

  def __init__(self):
    super(Net,self).__init__()
    # 1 input image channel, 6 output channels, 3x3 square convolution
    # kernel
    self.conv1 = nn.Conv2d(1,6,3)
    self.conv2 = nn.Conv2d(6, 16, 3)
    # an affine operation: y = Wx + b
    self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)
  
  def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

  def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features






## Step 2: Implement One Forward Pass

In [78]:
# create an object of class Net
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [83]:
# Learnable parameters of ann
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

10
torch.Size([10, 84])


In [86]:
# Create input image 
# For example, nn.Conv2d will take in a 4D Tensor of nSamples x nChannels x Height x Width.
# If you have a single sample, just use input.unsqueeze(0) to add a fake batch dimension.
input = torch.randn(1, 1, 32, 32)
print(input)

tensor([[[[-1.5450,  0.6333,  0.2145,  ..., -0.3885, -0.0073,  0.3841],
          [-1.0216, -0.0679, -0.5060,  ...,  0.8411,  0.3317, -0.1294],
          [ 0.2395, -0.2879,  0.4470,  ...,  0.8691, -0.5466,  0.2517],
          ...,
          [-1.0359,  0.5745,  0.5157,  ...,  0.3446, -1.2110, -0.1271],
          [-0.3917,  0.5699,  0.8173,  ...,  0.2959,  0.0227, -2.4538],
          [ 0.3743, -0.4678, -1.1302,  ..., -0.9404, -0.0515,  0.0845]]]])


torch.Size([1, 1, 32, 32])

In [87]:
# Let’s try a random 32x32 input. Note: expected input size of this net (LeNet) is 32x32. 
# To use this net on the MNIST dataset, please resize the images from the dataset to 32x32.
out = net(input)
print(out)

tensor([[-0.0714, -0.0180, -0.1057,  0.0404,  0.0144,  0.0483, -0.1364,  0.0540,
          0.0521, -0.1181]], grad_fn=<AddmmBackward>)


In [88]:
# Zero the gradient buffers of all parameters and backprops with random gradients:

net.zero_grad()
out.backward(torch.randn(1, 10))

## Step 3: Compute Loss Function

In [89]:
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(1.0313, grad_fn=<MseLossBackward>)


## Step 4: BackProp

In [90]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([-0.0036,  0.0253,  0.0073, -0.0104,  0.0180, -0.0140])


## Step 5: Update Weights

In [91]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update